SPREADSHEET_ID = '1MMKBimsoecrYKZD7JtrwRpVBrFfpxq0uJipmzL9DTWw'
SCHEDULE_SHEET_GID = 385579725

ALLOWED_EMAILS = [
    'davidgao734@gmail.com',
    'stefa.miva@gmail.com',
]

# Exact column headers from the Google Form responses sheet
COL_TS     = "Timestamp"
COL_MONTH  = "Месяц"
COL_NAME   = "Имя и Фамилия"
COL_MORN   = "Утренние смены (выбрать даты)"
COL_EVE    = "Вечерние смены (выбрать даты)"
COL_STORES = "В каких кафе вы можете работать "

SHIFTS = ["Утро", "Вечер"]
SHIFT_LABEL = {"Утро": "День", "Вечер": "Ночь"}

DEFAULT_STORE_WEIGHTS = {
    "Красная Площадь": 1.5,
    "Советов": 1.0,
    "Бон Пассаж": 1.0,
    "Краснодар Красная площадь": 1.5,
    "Краснодар Оз молл": 2.0,
    "Краснодар Галерея": 1.5,
    "Краснодар Володи Головатого": 1.0,
    "Черноморский": 0.5,
    "Грин Парк": 1.0,
}

MONTHS_RU = [
    "Январь", "Февраль", "Март", "Апрель", "Май", "Июнь",
    "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь",
]

STRINGS: dict[str, dict] = {
    "en": {
        "app_title": "Schedule Optimizer — Boba Rabbit",
        "sign_in_desc": "Employee schedule optimization using CP-SAT.",
        "sign_in_btn": "Sign in with Google",
        "access_denied": "Access denied. Your account is not authorized.",
        "sign_out": "Sign out",
        "month_label": "Month",
        "solver_expander": "Solver Settings",
        "max_shifts_label": "Max shifts per employee",
        "time_limit_label": "Time limit (sec)",
        "output_sheet_label": "Output sheet name",
        "load_btn": "Load Data",
        "loading_msg": "Loading from Google Sheets...",
        "loaded_toast": "Data loaded!",
        "load_error": "Load error: {err}",
        "page_title": "Schedule Optimization",
        "no_data_info": "Click «Load Data» in the sidebar to get started.",
        "col_missing_error": "Column «{col}» not found. Check the sheet structure.",
        "metric_responses": "Responses this month",
        "metric_employees": "Employees",
        "metric_cafes": "Cafes",
        "no_month_warning": "No data for {month}. Select another month or reload.",
        "store_settings_header": "Cafe Settings",
        "store_settings_caption": "Adjust priority weight and staffing per cafe.",
        "col_store": "Cafe",
        "col_weight": "Weight",
        "col_morning": "Morning (ppl)",
        "col_evening": "Evening (ppl)",
        "weight_help": "Cafe priority in optimization (higher = more important to fill)",
        "morning_help": "Staff needed for morning shift",
        "evening_help": "Staff needed for evening shift",
        "run_btn": "Run Optimization",
        "solving_spinner": "Solving (up to {sec} sec)...",
        "opt_error": "Optimization error: {err}",
        "status_label": "Status",
        "metric_required": "Shifts required",
        "metric_filled": "Filled",
        "metric_missing": "Unfilled",
        "coverage_header": "Coverage by Day and Cafe",
        "date_col": "Date",
        "emp_dist_header": "Shift Distribution by Employee",
        "emp_col": "Employee",
        "shifts_col": "Shifts assigned",
        "deviation_col": "Deviation from avg",
        "save_btn": "Save to Google Sheets",
        "saving_spinner": "Saving...",
        "save_success": "Saved!",
        "save_error": "Save error: {err}",
        "download_btn": "Download CSV",
        "months": ["January", "February", "March", "April", "May", "June",
                   "July", "August", "September", "October", "November", "December"],
    },
    "ru": {
        "app_title": "Оптимизация расписания — Боба Кролик",
        "sign_in_desc": "Оптимизация расписания сотрудников с помощью CP-SAT.",
        "sign_in_btn": "Войти через Google",
        "access_denied": "Доступ запрещён. Ваш аккаунт не авторизован.",
        "sign_out": "Выйти",
        "month_label": "Месяц",
        "solver_expander": "Настройки солвера",
        "max_shifts_label": "Макс. смен на сотрудника",
        "time_limit_label": "Время решения (сек)",
        "output_sheet_label": "Лист для записи в Sheets",
        "load_btn": "Загрузить данные",
        "loading_msg": "Загружаем из Google Sheets...",
        "loaded_toast": "Данные загружены!",
        "load_error": "Ошибка загрузки: {err}",
        "page_title": "Оптимизация расписания",
        "no_data_info": "Нажмите «Загрузить данные» в боковой панели для начала работы.",
        "col_missing_error": "Столбец «{col}» не найден. Проверьте структуру таблицы.",
        "metric_responses": "Ответов за месяц",
        "metric_employees": "Сотрудников",
        "metric_cafes": "Кафе",
        "no_month_warning": "Нет данных за {month}. Выберите другой месяц или перезагрузите данные.",
        "store_settings_header": "Настройки кафе",
        "store_settings_caption": "Измените вес приоритета и количество сотрудников на смену для каждого кафе.",
        "col_store": "Кафе",
        "col_weight": "Вес",
        "col_morning": "Утро (чел.)",
        "col_evening": "Вечер (чел.)",
        "weight_help": "Приоритет кафе в оптимизации (выше = важнее заполнить)",
        "morning_help": "Сколько сотрудников нужно на утреннюю смену",
        "evening_help": "Сколько сотрудников нужно на вечернюю смену",
        "run_btn": "Запустить оптимизацию",
        "solving_spinner": "Решаем задачу (до {sec} сек)...",
        "opt_error": "Ошибка оптимизации: {err}",
        "status_label": "Статус",
        "metric_required": "Требуется смен",
        "metric_filled": "Заполнено",
        "metric_missing": "Не заполнено",
        "coverage_header": "Покрытие по дням и кафе",
        "date_col": "Дата",
        "emp_dist_header": "Распределение смен по сотрудникам",
        "emp_col": "Сотрудник",
        "shifts_col": "Смен назначено",
        "deviation_col": "Отклонение от среднего",
        "save_btn": "Сохранить в Google Sheets",
        "saving_spinner": "Записываем...",
        "save_success": "Записано!",
        "save_error": "Ошибка записи: {err}",
        "download_btn": "Скачать CSV",
        "months": ["Январь", "Февраль", "Март", "Апрель", "Май", "Июнь",
                   "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"],
    },
}
